### ISSUE TITLE
can't call 

### ISSUE THREAD

**Issue by ZTFtrue** [Magisk-Modules-Repo/callrecorder-skvalex#11]
I can't call and receiver call .  

```
Android version: 12
Magisk: Zygisk enable , version 24.3
```

**Comment by startekselva** [comment]
Install the app and magiak module  and grand permission you need to buy the app from play store

**Comment by ZTFtrue** [comment]
I bought this app from play store and allow this app to use related permissions. 

when i install  magiak module ,  the app  can't call and receiver call.  when i uninstall magisk module , the app can record . 

Now , I using the app without magisk module
