### ISSUE TITLE
Make it work as a answering machine 

### ISSUE THREAD

**Issue by varunpilankar** [Magisk-Modules-Repo/callrecorder-skvalex#12]
Hi @skvalex ,

Can this module/app can help me make it work as a answering machine via Tasker.

Here is what it would look like:

1. Event --> Call From Unknown number
2. Task --> Start the Call Recording
3. Task --> Answer the call
4. Task --> Play Audio message to Call Stream Uplink (without putting the phone on speaker)
5. Task --> End the call & Stop Recording

My 90% logic is working using Tasker but I'm not able to play audio into call stream Uplink

Is there any way to achieve this scope?

**Comment by skvalex** [comment]
Hi, no, there's no such functionality.

**Comment by varunpilankar** [comment]
Noted.

Apart from your module/app.

Can this be achieved using Audio Manager API?

**Comment by skvalex** [comment]
@varunpilankar no, as far as I know Android doesn't have such API
