### ISSUE TITLE
 OPPO Find X5 Lite

### ISSUE THREAD

**Issue by sutex** [Magisk-Modules-Repo/callrecorder-skvalex#15]
I have the OPPO Find X5 Lite, and unlocked the bootloader, by switching the OEM unlocking to "on" in the developer options. I assumed this would give root access to the full latest version of  skvalex Call Recorder, yet I'm still unable to record both side of a phone conversation. Do I need this module as well? Or is there something in settings I need to do?

**Comment by skvalex** [comment]
If providing root access wasn't enough, then try this magisk module

Anyway, it's not an issue with the module, so I'm closing it
