### ISSUE TITLE
Callrecording doesnt work propperly anymore, Android 13 Latest security patch 5 februari 2023 (CUSTOM ROM)

### ISSUE THREAD

**Issue by Hot12345** [Magisk-Modules-Repo/callrecorder-skvalex#17]
Hi Alexander, 

I have problems with the call recording app (root)... 

Im using the Oneplus 8 Pro, Evolution X Rom.
Android 13 Google security patch 5 Februari 2023. 

My callrecording app; doesnt record sound anymore. I hear only a blip/crack sound and that is only thing what I hear. 
I want that you debugg this issue with me.. Because before the security update everthing was working fine without any problems.

I installed the module from Github.  I use only this module as root, no other modules being installed.
removed and reinstalled the module and started again and still not working.. 

If I wanna share a audio clip, it doesnt record anything, because there are no wave spikes, sounds. It something happend in the security patch of Android/Google.

Can you help me with this?

Kind Regards,

![Screenshot_20230209-092834_CallRecorder](https://user-images.githubusercontent.com/29144713/217786202-2aa8fc24-dbb9-4740-a006-e92d0bae412f.png)
![Screenshot_20230209-092820_CallRecorder](https://user-images.githubusercontent.com/29144713/217786205-2f3ae873-4c07-4e73-a25e-daa825dc411f.png)
![Screenshot_20230209-092813_CallRecorder](https://user-images.githubusercontent.com/29144713/217786207-0968e0ba-dd10-4101-be4d-2a627582e213.png)
![Screenshot_20230209-092809_CallRecorder](https://user-images.githubusercontent.com/29144713/217786213-5577e0b8-1c6d-4355-a0ce-b2205da7fd6e.png)
![Screenshot_20230209-092711_Settingss](https://user-images.githubusercontent.com/29144713/217786217-ffc81e42-00cf-4f8f-bb07-f5b106b0eedf.png)

**Comment by skvalex** [comment]
Please check the 3.5.5 alpha01 version from xda https://forum.xda-developers.com/t/android-4-0-call-recorder-skvalex-record-phone-calls-from-the-phone-line.1441643/post-87991029

Uninstall Magisk module to make sure it doesn't affect the fix

**Comment by Hot12345** [comment]
> Please check the 3.5.5 alpha01 version from xda https://forum.xda-developers.com/t/android-4-0-call-recorder-skvalex-record-phone-calls-from-the-phone-line.1441643/post-87991029
> 
> Uninstall Magisk module to make sure it doesn't affect the fix

Thankyouuuu!! It works again!
What I did, is delete the module and only installed the apk,  with root what I had it before.

What is the issue that Google being changed something that this breaks?

Again super Thanks.

**Comment by skvalex** [comment]
@Hot12345 I've replied on xda to this question: https://forum.xda-developers.com/t/android-4-0-call-recorder-skvalex-record-phone-calls-from-the-phone-line.1441643/post-87999863
