### ISSUE TITLE
Recording issue with Google Voice incoming calls

### ISSUE THREAD

**Issue by LinuxETC** [Magisk-Modules-Repo/callrecorder-skvalex#2]
An observational note and issue.
I noticed with Android v11 (unlocked and rooted via Magisk) that the application is no longer recording incoming phone calls that go through Google Voice.  This was not an issue with Android v10.  There is a "blank recording" for the duration of the call that is empty/silence.

Outgoing calls on Google Voice are recording as expected.

Cellular calls, both incoming and outgoing are recording as expected.

Smartphone is a Google Pixel 3 (aka "blueline") running the latest build (RQ1A.210105.003).  Call Recorder is using the "default settings" (nothing tinkered with nor changed at this time).

Questions and/or feedback are welcomed.  Thanks in advance.

**Comment by mainsm** [comment]
I was able to get everything working this morning after experiencing all of
the issues you've had.  One thing to keep in mind is that Skvalex does not
seem to be able to record any calls that go over data/wifi.  So in your
Phone app and Google Voice app, set your calls to be handled by your
carrier.  Even after I did this, I was still getting inexplicable problems
with Google Voice. I was just hearing silence in the calls I sent or
received.  I fixed this by uninstalling Google Voice, rebooting, and
installing it again.  I then had to set Google Voice to be handled by the
carrier again.  After that, I was able to record any calls I received or
sent over Google Voice.

I hope this helps.

**Comment by LinuxETC** [comment]
Looks like that was the issue and resolution.  Thanks!

I am not sure how or why Google Voice changed the default settings from "carrier based" to "data/wifi" to be honest, but then again I have been using this for 3+ years now.

I do appreciate the reply and assistance once again.
