### ISSUE TITLE
Call Recording Not Working

### ISSUE THREAD

**Issue by SMagic11** [Magisk-Modules-Repo/callrecorder-skvalex#5]
I have a rooted Mi Note 8 pro phone, magisk is installed & also installed the skvalex call recorder but it's not working at all. Tried every combination but not the call recording is blank & not able to hear any side.

**Comment by 3033071101** [comment]
> I have a rooted Mi Note 8 pro phone, magisk is installed & also installed the skvalex call recorder but it's not working at all. Tried every combination but not the call recording is blank & not able to hear any side.

**Comment by callmedanielpida** [comment]
I have the same issue with my pixel 5a. Does anyone have a suggestion or should we buy the full version of the app?

**Comment by skvalex** [comment]
Can you try to change recording format to mp3? Some people reported that it helps

**Comment by callmedanielpida** [comment]
I will try that and let you know
