### ISSUE TITLE
Android.Agent.GEN45177

### ISSUE THREAD

**Issue by chelkaz** [Magisk-Modules-Repo/callrecorder-skvalex#7]
callrecorder-skvalex
https://www.virustotal.com/gui/file/a353f08d78019f57ef5bc896a7133f65663373c8e0e1c606d337494490635119?nocache=1
how to explain it?

**Comment by skvalex** [comment]
I just sent a request to CAT-QuickHeal support. Will see what they reply.
Recently avast also detected the app as a malware, but after I contacted them, they promised to add the app to their allowlist.

**Comment by chelkaz** [comment]
> Will see what they reply.

Great, we'll follow. Write here as you become aware.

**Comment by skvalex** [comment]
Still got no reply from their support.

But I managed to find out that they flag the app like this by recompiling apk with some features off and checking it again on virustotal and again. It turned out to be my empty accessibility service. Here's the code for this service:

```
package org.skvalex.cr.full.service

import android.accessibilityservice.AccessibilityService
import android.view.accessibility.AccessibilityEvent

class MyAccessibilityService : AccessibilityService() {
    companion object {
        private const val TAG = "MyAccessibilityService"
    }

    override fun onInterrupt() {
    }

    override fun onAccessibilityEvent(p0: AccessibilityEvent?) {
    }
}
```

**Comment by skvalex** [comment]
Closing this issue as there's no more detections on virustotal.com
