### ISSUE TITLE
Android 12 compatibility 

### ISSUE THREAD

**Issue by smgchosen** [Magisk-Modules-Repo/callrecorder-skvalex#9]
Hi, someone can inform me if Call Recorder is compatible with Android 12 on Samsung devices?

**Comment by smgchosen** [comment]
Hi Alex. You closed thread but I don't know the answer?

**Comment by skvalex** [comment]
Use xda forum for such kind of questions https://forum.xda-developers.com/t/android-4-0-call-recorder-skvalex-record-phone-calls-from-the-phone-line.1441643/
